### ISSUE TITLE
The sensor controller randomly disconnects after 30-90 minutes

### ISSUE THREAD

**Issue by matt24smith** [matt24smith/greenbox#2]
Some notes:
- https://github.com/espressif/arduino-esp32/issues/119
- add delay after client.printf() statements
- specify content length

**Comment by matt24smith** [comment]
Investigate AP autoconnect

https://github.com/esp8266/Arduino/issues/1615

**Comment by matt24smith** [comment]
Disconnect sensor from local AP???

**Comment by LucasFeliciano21** [comment]
Hi Matt, 

I'm a bit confused about the connection reset, where did you change the

> add delay after client.printf() statements
>specify content length

Because in the FSbrowser example for Web server there is no usage of client.printf()

Thanks

**Comment by matt24smith** [comment]
it appears that the disconnect was a bug in the wifiserver code: The server disconnects only when attempting to both create an AP and connect to a different AP. Problem was fixed by having device create an AP without connecting to local network

**Comment by LucasFeliciano21** [comment]
I solved this by changing the server to the async version, It's way much faster and is implemented based on interrupt callbacks, so is way more responsive to requests. Thanks man!
